name: flutter_application_1
description: Solar Match 2026 - App de instalación de paneles solares
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  http: ^1.2.0
  geolocator: ^12.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/data/productos_locales.json